### ISSUE TITLE
Display Mode Functionality

### ISSUE THREAD

**Issue by Tyluur** [2011Scape/rs-client#1]
All display modes need to be supported by the client.

**Comment by Tyluur** [comment]
Status: DirectX - 0%
OpenGL: 50%
Software: 50%

**Comment by Tyluur** [comment]
OpenGL Caps at 40FPS for some users.

![](https://i.imgur.com/HlCE25s.png)

Right (2011Scape)
Left (Avalon718)

**Comment by Paleocene** [comment]
In the current client (from the 2011Scape website) only safe mode works for linux users

**Comment by ipkpjersi** [comment]
> In the current client (from the 2011Scape website) only safe mode works for linux users

I'm also experiencing this on Linux even with the AppImage:

![](https://i.imgur.com/gsjf9A3.png)

The AppImage does not provide any errors or anything as to why this happens even when ran from the command line, this is the command line output before switching display modes:
```
2024-01-08 17:01:04 [main] INFO  net.runelite.launcher.Launcher - 2011Scape Launcher version 2.6.3-SNAPSHOT
2024-01-08 17:01:04 [main] INFO  net.runelite.launcher.Launcher - Launcher configuration:
 debug: false
 nodiffs: false
 skip tls verification: false
 noupdates: false
 safe mode: false
 scale: system
 client arguments: none
 jvm arguments: none
 hardware acceleration mode: AUTO
 launch mode: REFLECT
2024-01-08 17:01:04 [main] INFO  net.runelite.launcher.Launcher - Using hardware acceleration mode: OFF
2024-01-08 17:01:05 [main] INFO  net.runelite.launcher.Launcher - Verified hash of 2011Scape.jar
Gtk-Message: 17:01:05.471: Failed to load module "xapp-gtk3-module"
sun.awt.image.ImageFormatException: Unsupported color conversion request
	at java.desktop/sun.awt.image.JPEGImageDecoder.readImage(Native Method)
	at java.desktop/sun.awt.image.JPEGImageDecoder.produceImage(Unknown Source)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
	at java.desktop/sun.awt.image.ImageFetcher.run(Unknown Source)
```

There is no additional output in the command line after switching display modes.
